@echo off
title RentFlow Reports Fixer
echo [1/3] Entering backend directory...
cd /d "%~dp0backend"
echo [2/3] Installing exceljs and types...
call npm install exceljs @types/exceljs
echo [3/3] Restarting the backend server...
echo [OK] Dependencies installed. Starting backend...
npm run start:dev
pause
