import { Injectable } from '@nestjs/common';
import * as PDFDocument from 'pdfkit';

export interface ReportMeta {
  title: string;
  generatedAt: Date;
  dateRange: string;
  companyName: string;
  logoUrl?: string;
}

@Injectable()
export class PdfRendererService {
  async renderReport(reportType: string, data: any, meta: ReportMeta): Promise<Buffer> {
    return new Promise((resolve) => {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));

      // Header
      this.generateHeader(doc, meta);
      
      // Content based on type
      if (reportType === 'income-statement') {
        this.renderIncomeStatement(doc, data);
      } else if (reportType === 'balance-sheet') {
        this.renderBalanceSheet(doc, data);
      } else if (reportType === 'trial-balance') {
        this.renderTrialBalance(doc, data);
      } else if (reportType === 'ar-aging') {
        this.renderArAging(doc, data);
      } else {
        doc.text('Report content visualization for ' + reportType + ' (PDF version pending detailed Layout)');
      }

      // Footer
      this.generateFooter(doc);
      
      doc.end();
    });
  }

  private generateHeader(doc: any, meta: ReportMeta) {
    doc.fillColor('#444444')
       .fontSize(20)
       .text(meta.companyName, 110, 50)
       .fontSize(10)
       .text(meta.title, 200, 50, { align: 'right' })
       .text(meta.dateRange, 200, 65, { align: 'right' })
       .moveDown();
    
    doc.strokeColor('#aaaaaa')
       .lineWidth(1)
       .moveTo(50, 90)
       .lineTo(550, 90)
       .stroke();
  }

  private generateFooter(doc: any) {
    doc.fontSize(10)
       .fillColor('#aaaaaa')
       .text('Generated by RentFlow - Page 1 of 1', 50, 780, { align: 'center', width: 500 });
  }

  private renderIncomeStatement(doc: any, data: any) {
    doc.fontSize(12).fillColor('#000000').text('Account', 50, 110).text('Amount', 400, 110, { align: 'right' });
    let y = 130;
    data.sections.forEach((s: any) => {
      doc.fontSize(11).font('Helvetica-Bold').text(s.sectionName, 50, y);
      y += 20;
      s.accounts.forEach((a: any) => {
        doc.font('Helvetica').fontSize(10).text(a.accountName, 60, y).text(this.formatNum(a.amount), 400, y, { align: 'right' });
        y += 15;
      });
      doc.font('Helvetica-Bold').text('Total ' + s.sectionName, 60, y).text(this.formatNum(s.total), 400, y, { align: 'right' });
      y += 25;
    });
    doc.rect(50, y, 500, 25).fill('#f3f4f6');
    doc.fillColor('#000000').font('Helvetica-Bold').text('Net Income', 60, y + 7).text(this.formatNum(data.netIncome), 400, y + 7, { align: 'right' });
  }

  private renderBalanceSheet(doc: any, data: any) {
    doc.fontSize(12).text('Category', 50, 110).text('Balance', 400, 110, { align: 'right' });
    let y = 130;
    // Assets
    doc.font('Helvetica-Bold').text('ASSETS', 50, y); y += 20;
    data.assets.sections.forEach((s: any) => {
      doc.font('Helvetica-Bold').fontSize(10).text(s.sectionName, 60, y); y += 15;
      s.accounts.forEach((a: any) => {
        doc.font('Helvetica').text(a.accountName, 70, y).text(this.formatNum(a.balance), 400, y, { align: 'right' });
        y += 15;
      });
      y += 5;
    });
    doc.font('Helvetica-Bold').text('Total Assets', 50, y).text(this.formatNum(data.assets.totalAssets), 400, y, { align: 'right' });
    y += 30;
    // Liabs & Equity... (simplified for start)
  }

  private renderTrialBalance(doc: any, data: any) {
     doc.fontSize(10).text('Code', 50, 110).text('Account', 100, 110).text('Debit', 350, 110, { align: 'right' }).text('Credit', 450, 110, { align: 'right' });
     let y = 130;
     data.rows.forEach((r: any) => {
       doc.font('Helvetica').text(r.accountCode, 50, y).text(r.accountName, 100, y).text(this.formatNum(r.debit), 350, y, { align: 'right' }).text(this.formatNum(r.credit), 450, y, { align: 'right' });
       y += 15;
       if (y > 750) { doc.addPage(); this.generateHeader(doc, { title: '', generatedAt: new Date(), dateRange: '', companyName: '' }); y = 110; }
     });
  }

  private renderArAging(doc: any, data: any) {
    doc.fontSize(9).text('Tenant', 50, 110).text('Current', 200, 110, { align: 'right' }).text('30-60', 270, 110, { align: 'right' }).text('Total', 500, 110, { align: 'right' });
    let y = 130;
    data.rows.forEach((r: any) => {
      doc.text(r.tenantName, 50, y).text(this.formatNum(r.current), 200, y, { align: 'right' }).text(this.formatNum(r.bucket30), 270, y, { align: 'right' }).text(this.formatNum(r.total), 500, y, { align: 'right' });
      y += 15;
    });
  }

  private formatNum(n: number) {
    return (n || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  }
}
